### ISSUE TITLE
How to make 'len2nfrag' and 'len2prob3pri' data?

### ISSUE THREAD

**Issue by wangxlab** [YosefLab/SymSim#4] opened 2019-11-06 21:48 UTC
Hi Xiuwei,

I am looking at the source code file, "simulation_functions.R" and line 124 'amplify_1cell' function.  In the beginning of the function, there are two data. 

 if (protocol=="nonUMI"){data(len2nfrag)} else   # line 127
 if(protocol=="UMI"){data(len2prob3pri)} else     # line 128

rownames(len2nfrag) is individual gene length numbers that can be obtained from 'gene_len_pool'  and names(len2prob3fri) is also individual gene length numbers.   I modified SymSim code and using my own 'gene_len_pool'   (let's call it 'gene_len_sanghoon').   'gene_len_sanghoon' has some new gene length numbers.  Therefore, I am getting error in line 180 and line 195;

line 195
prob_vec <- len2prob3pri[as.character(gene_len[trans_idx])]    # some prov_vec are 'NA"

It is because some of gene length numbers in 'gene_len_sanghoon' don't exist in len2nfrag or len2prob3fri. Could you explain how you made  len2nfrag and len2prob3fri based on gene length numbers?   Then, I can make the data myself to match with 'gene_len_sanghoon' 

Thank you!
Sanghoon

**Comment by xiuweiz** [comment] 2019-12-19 23:50
Hi Sanghoon,
The ways to calculate len2nfrag and len2prob3fri are different as the former corresponds to nonUMI protocol and the latter corresponds to UMI protocol. For both cases, first you need to define some parameters which are used to select valid fragments. The parameters and values we used are as follows:

read_len <- 100 # read length
max_frag_len=1000 # maximum fragment length
expected_gap=200 # expected gap (since we assume getting paired-end reads)

For `len2nfrag`, given a gene length, we simulate 500 times the process of randomly making cuts to the full length sequence with probability `frag_eff` (calculated below). The pool of gene lengths are taken from gene lengths of hg38. (This is why when you use other gene lengths you don't find corresponding values in the pre-computed `len2nfrag` variable.)

frag_eff=1/(2*read_len+expected_gap)
all_glength <- sort(unique(hg38_gene_len), decreasing = F)

len2nfrag <- matrix(0, length(all_glength), 500)
rownames(len2nfrag) <- as.character(all_glength)
for (glength in all_glength){
  for (b in 1:500){
    x <- c(1, which(runif(glength) < frag_eff), glength)
    d <- x[2:length(x)] - x[1:length(x)-1]
    len2nfrag[as.character(glength), b] <- sum((d > read_len) &  (d < max_frag_len))
  }
}

To calculate `len2prob3fri` it's actually easier as for the case of keeping only the valid 3' fragments we have theoretical results so we don't need to perform simulation as done for `len2nfrag`. You can find the formula of how to calculate `len2prob3fri` in the supplementary information in the paper. Please let me know if you have any further questions.

**Comment by beyondpie** [comment] 2020-05-30 15:03
@xiuweiz @wangxlab 
From the current package, I can find the "len2nfrag", but cannot find the "len2prob3pri". I need to generate it myself?

**Comment by beyondpie** [comment] 2020-05-30 15:16
@xiuweiz 
I notice that on the latest commit, the data has been deleted (len2prob3pri). But in source code data.R, there still exists the line to include the data. 

So based on the latest commit, we actually don't need len2prob3pri, right ?

**Comment by xiuweiz** [comment] 2020-05-30 15:22
@beyondpie We don't need to load len2prob3pri, I shall delete it from data.R.

**Comment by beyondpie** [comment] 2020-05-30 15:42
@xiuweiz 
Thank you! I read the codes and notice that there is no need for this.
BTW, do you have a rough time estimation for generating the data? For example, if I use 10^5 cells and 10^4 genes, the program seems to keep running all the time ?

**Comment by xiuweiz** [comment] 2020-05-30 15:52
> @xiuweiz
> Thank you! I read the codes and notice that there is no need for this.
> BTW, do you have a rough time estimation for generating the data? For example, if I use 10^5 cells and 10^4 genes, the program seems to keep running all the time ?

Yes that will take a long time. The current implementation of adding technical noise by simulating the lab procedures is the most time consuming step. To generate 100,000 cells, it's better that you parallelize the task. I have not tested this exact dimension with the current version (I tried to speed up a bit) but I suppose getting 10,000 cells with technical noise would takes hours.

**Comment by beyondpie** [comment] 2020-05-30 15:59
@xiuweiz 
Thank you for your reply!  Do you have any suggestions on how to parallelize the task if I want to maintain the population structures among the cells?

**Comment by xiuweiz** [comment] 2020-05-30 16:15
You can parallelize only the True2ObservedCounts() function as this is the function which takes more time. Once the true counts are generated the population structure is there. True2ObservedCounts() basically add technical noise to each cell independently. Please let me know if you have further questions regarding this. We should implement some built in function to allow the parallelization for True2ObservedCounts(). I'd also appreciate if you have any recommendation of package for parallelization in R.

**Comment by xiuweiz** [comment] 2020-05-30 16:18
We can parallelize the second part of SimulateTrueCounts() too, after the EVFs are calculated for all cells. The EVFs would already have the population structure. Then from EVFs to true counts can be parallelized. But of course that would require some re-structuring of the SimulateTrueCounts() code.

**Comment by beyondpie** [comment] 2020-05-30 16:29
@xiuweiz 
Thank you very much! This is already helpful!   The simplest way to parallelize might directly use the package of `parallelization` as for as I know, which uses the multiple CPUs to run the loop structure. Otherwise, we need Rcpp, I think. 

BTW,  if I want to model case/control experiments in 20 individuals (case has 10 individuals, control has 10 individuals, e.g.). Each individual has around 1000 cells. The cells could be T cells, B cells, or other types.    I plan to model the batch effect on individuals and cell types.   
If you have any suggestions on this, that would be great!
Songpeng

**Comment by xiuweiz** [comment] 2020-05-30 16:37
Thanks for recommending the parallel package!
You can use the input tree (the phyla argument) to represent the number of cell types and relationship between them. 
Individuals would correspond to batches. 
The differences between case and control is not just batch effect but also some biological difference, right?

**Comment by beyondpie** [comment] 2020-05-30 16:45
Thank you!
Yes, the case/control is the biological experiment, e.g., some individual takes something or responds to something while others not.

**Comment by xiuweiz** [comment] 2020-05-30 16:55
For the 10 control individuals, you can use 10 batches, and use the input tree for cell type differences. 
For the 10 case samples, you can do the same. 
Now, in order to add biological difference between control and case, I'm not completely sure as I didn't generate such scenario before, but I would try to use slightly different evf_center values for case and control. 
Your scenario is good example and I'd be interested in testing whether changing evf_center can actually do the job.

**Comment by xiuweiz** [comment] 2020-05-30 16:58
My response is in line with what you said "modify the EVF for genes to get different means and variances under case/control". But keep in mind that the evf variance Sigma will change the heterogeneity of your subpopulations.

**Comment by xiuweiz** [comment] 2020-05-30 17:01
Now, as I talk about batch effects, I realize that adding batch effect may cause problem if one wants to parallelize the True2ObservedCounts function. I will take the part of adding batch effect out from the True2ObservedCounts function and make it an independent function.

**Comment by beyondpie** [comment] 2020-05-30 17:07
Thank you for your responses!
I will try both the evf_center and Simga. I think if I want to divide the genes into different modules, I should sampling evf_center for each gene from several common evf_center mean, right?

**Comment by beyondpie** [comment] 2020-05-30 17:10
> Now, as I talk about batch effects, I realize that adding batch effect may cause problem if one wants to parallelize the True2ObservedCounts function. I will take the part of adding batch effect out from the True2ObservedCounts function and make it an independent function.

Thank you for letting me this. I can firstly simulate small samples considering the time complexity. Actually, I notice that it also uses lots of memory. I remember when I want to generate 10^5 cells and 10^4 genes, it roughly takes 20G memory (Maybe I am wrong) ...

**Comment by xiuweiz** [comment] 2020-05-30 18:06
> Thank you for your responses!
> I will try both the evf_center and Simga. I think if I want to divide the genes into different modules, I should sampling evf_center for each gene from several common evf_center mean, right?

"gene effect" is the vector which controls behavior of genes. If you want to have gene modules where genes co-express, first these genes need to be controlled by the same EVFs. For example, if we say that evf1 and evf2 affect these genes, then in the gene-effect vectors of these genes, we need to make sure that the corresponding values are not zeros. Second, you may want these genes to co-express only in one cell type. In this case, we need to set evf1 and evf2 to be 0 for other cell types. 
I don't think one can generate co-expressed gene modules directly by playing the arguments of the SimulateTrueCounts function. It'll require some altering of the evf and gene-effect vectors inside the function as I described above.
If you need to use the gene-module function and if you can wait (pls let me know more details: are you simulating discrete population or continuous population, how many co-expressed gene modules you want, and for each gene module does it exist in only one or two cell types ),  I may be able to add that within two weeks. 

Also FYI another scRNA-seq simulator SERGIO can generate data guided by a regulatory network, so you should get co-express gene modules by designing the input network structure.

**Comment by xiuweiz** [comment] 2020-05-30 18:08
I will close this issue since we have been discussing various topics here. Please open new issues for further questions/comments.

**Closed by xiuweiz** 2020-05-30 18:08 UTC
